name: medai

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - cudatoolkit=12.1
  - lightning=2.*
  - torchmetrics=0.*
  - hydra-core=1.*
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  - numpy=1.*
  - pandas=2.*
  - matplotlib=3.*
  - scikit-learn=1.*
  - scikit-image=0.*
  - tensorboardx=2.*
  - pip>=23
  - pip:
      - torch==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - torchaudio==2.1.0+cu121
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
      - tqdm
      - opencv-python
      - timm
      - grad-cam
      - efficientnet-pytorch
      - dominate
      - pyyaml
      - ttach
      - medpy
      - seaborn
      - segmentation-mask-overlay
      - thop
      - h5py
      - batchgenerators
      - nibabel
      - monai
      - einops